import type { Metadata } from "next";

// The Vault dApp is a standalone Vite build shipped as static files under
// /app (see landing/public/app, generated by `npm run build:app`). We expose it
// at the clean same-origin path /vault by framing /app/vault.html full-bleed.
// A Next rewrite to the static .html works locally but 404s on Vercel, so this
// real page route is the reliable way to keep the /vault URL. Same origin, so
// the wallet's injected provider (window.ethereum) is available inside the frame.
export const metadata: Metadata = {
  title: "Vault",
  description:
    "Sphynx investor Vault — connect, deposit, withdraw. Live on Robinhood Chain mainnet: unaudited, deposits capped, no track record.",
};

export default function VaultPage() {
  return (
    <>
      <style>{`html,body{margin:0;height:100%;overflow:hidden;background:#0b0d10}`}</style>
      <iframe
        src="/app/vault.html"
        title="Sphynx Vault"
        style={{
          position: "fixed",
          inset: 0,
          width: "100%",
          height: "100%",
          border: 0,
          display: "block",
        }}
        allow="clipboard-write; clipboard-read"
      />
    </>
  );
}
